//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendario
    {
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<int> NrPartite { get; set; }
        public int Level { get; set; }
        public string NomeSquadraC { get; set; }
        public string NomeSquadraF { get; set; }
        public Nullable<int> RetiC { get; set; }
        public Nullable<int> RetiF { get; set; }
        public int Stagione { get; set; }
        public int SottoStagione { get; set; }
        public Nullable<int> Rigori { get; set; }
        public string TestoRigori { get; set; }
        public Nullable<int> PrgStagione { get; set; }
    }
}
