//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificaGiocatori
    {
        public int IDGiocatore { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public int Stagione { get; set; }
        public Nullable<int> Presenze { get; set; }
        public Nullable<int> Reti { get; set; }
        public Nullable<int> Assist { get; set; }
        public Nullable<int> Punti { get; set; }
        public Nullable<int> Penalita { get; set; }
        public Nullable<int> IDSquadra { get; set; }
        public string NomeSquadra { get; set; }
    }
}
