//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LHAL_AppEntities : DbContext
    {
        public LHAL_AppEntities()
            : base("name=LHAL_AppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassificaManuale> ClassificaManuale { get; set; }
        public virtual DbSet<Giocatore> Giocatore { get; set; }
        public virtual DbSet<Girone> Girone { get; set; }
        public virtual DbSet<GironeStagione> GironeStagione { get; set; }
        public virtual DbSet<Partita> Partita { get; set; }
        public virtual DbSet<Rosa> Rosa { get; set; }
        public virtual DbSet<Squadra> Squadra { get; set; }
        public virtual DbSet<Stagione> Stagione { get; set; }
        public virtual DbSet<Tabellino> Tabellino { get; set; }
        public virtual DbSet<Calendario> Calendario { get; set; }
        public virtual DbSet<ClassificaGiocatori> ClassificaGiocatori { get; set; }
        public virtual DbSet<ClassificaPortieri> ClassificaPortieri { get; set; }
        public virtual DbSet<DatePartite> DatePartite { get; set; }
        public virtual DbSet<GiocatoreOverview> GiocatoreOverview { get; set; }
        public virtual DbSet<PartitaSquadre> PartitaSquadre { get; set; }
        public virtual DbSet<PartitePerSquadra> PartitePerSquadra { get; set; }
        public virtual DbSet<Tabellini> Tabellini { get; set; }
    
        public virtual ObjectResult<GetClassifica_Result> GetClassifica(Nullable<int> iDStagione, Nullable<int> iDGirone)
        {
            var iDStagioneParameter = iDStagione.HasValue ?
                new ObjectParameter("IDStagione", iDStagione) :
                new ObjectParameter("IDStagione", typeof(int));
    
            var iDGironeParameter = iDGirone.HasValue ?
                new ObjectParameter("IDGirone", iDGirone) :
                new ObjectParameter("IDGirone", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClassifica_Result>("GetClassifica", iDStagioneParameter, iDGironeParameter);
        }
    
        public virtual ObjectResult<GetClassificaCompleta_Result> GetClassificaCompleta(Nullable<int> iDStagione)
        {
            var iDStagioneParameter = iDStagione.HasValue ?
                new ObjectParameter("IDStagione", iDStagione) :
                new ObjectParameter("IDStagione", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClassificaCompleta_Result>("GetClassificaCompleta", iDStagioneParameter);
        }
    
        public virtual ObjectResult<GetDettaglioGiocatore_Result> GetDettaglioGiocatore(Nullable<int> iDGiocatore)
        {
            var iDGiocatoreParameter = iDGiocatore.HasValue ?
                new ObjectParameter("IDGiocatore", iDGiocatore) :
                new ObjectParameter("IDGiocatore", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDettaglioGiocatore_Result>("GetDettaglioGiocatore", iDGiocatoreParameter);
        }
    
        public virtual ObjectResult<GetDettaglioPartita_Result> GetDettaglioPartita(Nullable<int> iDPartita)
        {
            var iDPartitaParameter = iDPartita.HasValue ?
                new ObjectParameter("IDPartita", iDPartita) :
                new ObjectParameter("IDPartita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDettaglioPartita_Result>("GetDettaglioPartita", iDPartitaParameter);
        }
    }
}
