//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiocatoreOverview
    {
        public int SquadraID { get; set; }
        public int StagioneID { get; set; }
        public int IDGiocatore { get; set; }
        public string SquadraNome { get; set; }
        public string Stagione { get; set; }
        public int IDStagione { get; set; }
        public string GiocatoreNome { get; set; }
        public string GiocatoreCognome { get; set; }
        public bool Attivo { get; set; }
        public int IDRosa { get; set; }
        public bool IsCapitano { get; set; }
        public bool IsAssistente { get; set; }
        public Nullable<int> NrMaglia1 { get; set; }
        public Nullable<int> NrMaglia2 { get; set; }
        public string Ruolo { get; set; }
        public bool ExTesserato { get; set; }
    }
}
