//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giocatore
    {
        public Giocatore()
        {
            this.Rosa = new HashSet<Rosa>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public bool ExTesserato { get; set; }
    
        public virtual ICollection<Rosa> Rosa { get; set; }
    }
}
