//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Girone
    {
        public Girone()
        {
            this.GironeStagione = new HashSet<GironeStagione>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<GironeStagione> GironeStagione { get; set; }
    }
}
