//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GironeStagione
    {
        public int ID { get; set; }
        public int IDGirone { get; set; }
        public int IDStagione { get; set; }
        public int IDSquadra { get; set; }
    
        public virtual Girone Girone { get; set; }
        public virtual Squadra Squadra { get; set; }
        public virtual Stagione Stagione { get; set; }
    }
}
