//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partita
    {
        public Partita()
        {
            this.Tabellino = new HashSet<Tabellino>();
        }
    
        public int ID { get; set; }
        public int SquadraC { get; set; }
        public int SquadraF { get; set; }
        public Nullable<int> RetiC { get; set; }
        public Nullable<int> RetiF { get; set; }
        public int Rigori { get; set; }
        public System.DateTime Data { get; set; }
        public int Stagione { get; set; }
        public int SottoStagione { get; set; }
        public System.DateTime UpdTMS { get; set; }
        public Nullable<int> PrgStagione { get; set; }
        public string ImgReferto { get; set; }
    
        public virtual Squadra Squadra { get; set; }
        public virtual Squadra Squadra1 { get; set; }
        public virtual Stagione Stagione1 { get; set; }
        public virtual ICollection<Tabellino> Tabellino { get; set; }
    }
}
