//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHAL.WebAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartitaSquadre
    {
        public int ID { get; set; }
        public int SquadraC { get; set; }
        public int SquadraF { get; set; }
        public string NomeSquadraC { get; set; }
        public string NomeSquadraF { get; set; }
        public Nullable<int> RetiC { get; set; }
        public Nullable<int> RetiF { get; set; }
        public System.DateTime Data { get; set; }
        public int Stagione { get; set; }
        public int SottoStagione { get; set; }
        public Nullable<long> DataInt { get; set; }
        public int Rigori { get; set; }
        public string TestoRigori { get; set; }
        public string TestoStagione { get; set; }
        public Nullable<int> PrgStagione { get; set; }
        public string ImgReferto { get; set; }
    }
}
